# Generated by Django 4.1.7 on 2023-04-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0002_alter_post_image_proflie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proflie',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
    ]
