# Generated by Django 4.1.7 on 2023-03-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0002_rename_postview_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
